targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          exclude:
            - "**.worker.dart"
      CommonLib|file_list_builder:
        options:
          enabled: true
          exclude:
            - "**.html"

builders:
  file_list_builder:
    import: "package:CommonLib/src/builder/builders.dart"
    builder_factories:
      - fileListBuilder
    build_extensions:
      .filelist:
        - .json
    build_to: cache
    auto_apply: root_package
    applies_builders:
      - CommonLib|file_list_cleanup_builder
    defaults:
      options:
        enabled: false
      generate_for:
        include:
          - web/**.filelist
          - example/**.filelist
          - benchmark/**.filelist
          - lib/**.filelist

  worker_builder:
    import: "package:build_web_compilers/builders.dart"
    builder_factories:
      - webEntrypointBuilder
    build_extensions:
      .dart:
        - .dart.bootstrap.js
        - .dart.js
        - .dart.js.map
        - .dart.js.tar.gz
        - .digests
    required_inputs:
      - .dart
      - .ddc.js
      - .ddc.module
      - .dart2js.module
    build_to: cache
    auto_apply: root_package
    defaults:
      generate_for:
        include:
          - web/**.worker.dart
          - example/**.worker.dart
          - benchmark/**.worker.dart
          - lib/**.worker.dart
      options:
        compiler: dart2js
      dev_options:
        dart2js_args:
          - --no-minify
      release_options:
        dart2js_args:
          - -O4
    applies_builders:
      - build_web_compilers|dart2js_archive_extractor

post_process_builders:
  file_list_cleanup_builder:
    import: "package:CommonLib/src/builder/builders.dart"
    builder_factory: "fileListCleanupBuilder"
    defaults:
      release_options:
        enabled: true