name: CommonLib
description: Basic shared components such as a logger, path manipulation and other general use functions.
version: 2.2.0
homepage: https://github.com/FarragoFiction/CommonLib
author: paradoxLands, jadedResearcher

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  js: any
  source_map_stack_trace: any

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: any

web:
  compiler:
    debug: dartdevc
