name: CommonLib
description: Basic shared components such as a logger, path manipulation and other general use functions.
version: 2.12.0
homepage: https://github.com/FarragoFiction/CommonLib
author: paradoxLands, jadedResearcher
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: any
  source_map_stack_trace: any
  build: any
  glob: any
  yaml: any

dev_dependencies:
  path: any
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  test: any
