name: CommonLib
description: Basic shared components such as a logger, path manipulation and other general use functions.
version: 1.24.2
homepage: https://github.com/FarragoFiction/CommonLib
author: paradoxLands, jadedResearcher

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  js: any
  source_map_stack_trace: any

dev_dependencies:
  test: ^0.12.0
