name: CommonLib
description: Basic shared components such as a logger, path manipulation and other general use functions.
version: 2.8.1
homepage: https://github.com/FarragoFiction/CommonLib
author: paradoxLands, jadedResearcher

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  js: any
  source_map_stack_trace: any

dev_dependencies:
  build_runner: ^1.6.0
  build_test: ^1.0.0
  build_web_compilers: ^2.3.0
  test: any
